name: Download and Push Files

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at UTC midnight

jobs:
  download_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout city-of-toronto-contracts-data
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}  # Use the branch or tag ref that triggered the workflow

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: pip install requests

      - name: Run download script
        run: python download.py

      - name: Commit and Push if Files Changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add .
          timestamp=$(date -u)
          git commit -m "Downloaded: ${timestamp}: commit: ${{github.sha}}" || exit 0
          # Use force push to push changes to the current branch
          git push origin HEAD:${{ github.ref }} --force
